
services:
  - type: web
    name: nextgen-admin
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn nextgen_netlab_admin.wsgi"
    plan: free
    preDeployCommand: "python manage.py migrate && python manage.py create_admin"
